Add `uDisplay` for `String` and inline `ufmt` functions
rust-embedded/heapless pull request #460
Opened 2024-02-28 09:24 UTC by lmbollen

Most likely the compiler already inlines the function calls, but afaik adding the annotation makes it more likely.

I could not build it locally due to:
```
   Compiling heapless v0.8.0 (/home/lucas/repos/heapless)
error[E0658]: use of unstable library feature 'build_hasher_simple_hash_one'
    --> src/indexmap.rs:1260:28
     |
1260 |     HashValue(build_hasher.hash_one(key) as u16)
     |                            ^^^^^^^^
     |
     = note: see issue #86161 <https://github.com/rust-lang/rust/issues/86161> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `heapless` due to previous error
```
But the implementation seems trivial and has been tested elsewhere.
I did not add `uDisplay` for `Vec` because the formatting is not trivial.

We might want to consider adding `uDebug`, but don't know what the rusty way to do so would be.

2024-02-29 12:57 UTC, reitermarkus commented
Apparently not yet: https://github.com/japaric/ufmt/issues/52

2024-02-29 19:05 UTC, reitermarkus commented
[`inline(always)` is almost never needed](https://std-dev-guide.rust-lang.org/policy/inline.html#what-about-inlinealways), so let's use only `inline`.

2024-06-30 22:25 UTC, Dirbaio commented
can you rebase and fix CI?

2024-07-01 07:43 UTC, lmbollen commented
> can you rebase and fix CI?

Done, also changed `#[inline(always)]` to `#[inline]`

2024-07-01 11:28 UTC, Dirbaio commented on Cargo.toml
> +defmt = { version = ">=0.2.0,<0.4", optional = true }
please don't autoformat Cargo.toml

2024-07-01 11:28 UTC, Dirbaio commented on CHANGELOG.md
> +- `ufmt` functions are annotated with `inline(always)`.
this no longer applies

2024-07-01 13:49 UTC, sosthene-nitrokey requested changes
This should be generic over the `StringInner` and the storage used.

2024-07-01 13:49 UTC, sosthene-nitrokey commented on src/ufmt.rs
>  use crate::{storage::Storage, string::String, vec::VecInner};
```suggestion
use crate::{storage::Storage, string::StringInner, vec::VecInner};
```

2024-07-01 13:49 UTC, sosthene-nitrokey commented on src/ufmt.rs
> +impl<const SIZE: usize> uDisplay for String<SIZE> {
```suggestion
impl<S: Storage> uDisplay for StringInner<S> {
```

2025-04-06 17:32 UTC, reitermarkus approved these changes

2025-04-06 17:34 UTC, merged